### ISSUE TITLE
Does not work with lua 5.2.3

### ISSUE THREAD

**Issue by srdgame** [xopxe/lumen#12]
Hi,

It does not work with lua 5.2.3 in my laptop, (Ubuntu Gnome 14.04 amd64). It works with luajit from openresty.  Below is the result running test.lua:

cch@cch-NV47H:~/mycode/lua/lumen/tests$ lua test.lua 
A says: going to sleep couple seconds
B says: waiting for a A to die
0 says: waiting for a 'ev' from A
cch@cch-NV47H:~/mycode/lua/lumen/tests$ /usr/local/openresty/luajit/bin/luajit-2.1.0-alpha test.lua 
A says: going to sleep couple seconds
B says: waiting for a A to die
0 says: waiting for a 'ev' from A
A says: emittig 'ev, data!'
0 says: received a 'ev' from A, with:   data!
0 says: going to kill A
B says: hear that A died
B says: going to error with message 'xxx'
2014/05/08 18:22:46 SCHED-WARNING: table: 0x406949a0 die on error, returning 1 parameters: test.lua:25: xxx
0 says: finishing, returning    data!
cch@cch-NV47H:~/mycode/lua/lumen/tests$

**Comment by rob-miller** [comment]
I have the same problem with LuaJIT as installed from torch (currently LuaJIT 2.1.0-beta1) on linux, which also reports _VERSION=='Lua 5.1'.  

The ugly but explicit version fix following the above is:

> 
        local ret = os.execute('sleep '..t)
        if _VERSION =='Lua 5.1' and type(jit) ~= 'table' and ret ~= 0
        or _VERSION ~='Lua 5.1' and ret ~= true
        or _VERSION =='Lua 5.1' and type(jit) == 'table' and ret ~= true then
                os.exit()
        end

but from my limited testing it seems you can just do:

>        
        local ret = os.execute('sleep '..t)
        if ret == 0 or ret == true then
            return
        end
        os.exit()

The second form works on Lua 5.2 on mac OSX and linux/LuaJIT as above.

**Comment by xopxe** [comment]
Thanks, I pushed your second option (and left the first commented as documentation)
