### ISSUE TITLE
Sched.sleep in milliseconds

### ISSUE THREAD

**Issue by milrrenmattar** [xopxe/lumen#14]
Hi,

I'm having trouble to use the sleep function of Sched in milliseconds. Already have tried some changes on the api to work as I want to but without success.

Anyone know how to do that?

**Comment by xopxe** [comment]
The simplest way, if you have luasocket installed, is to add this in your program:
```
local socket = require 'socket'
sched.get_time = socket.gettime 
sched.idle = socket.sleep
```

This is what tasks.selector-luasocket does. Also, instead of that previous fragment you can do a ```require 'tasks.selector-luasocket'``` which will do the redefinition for you.

There is also selector-nixio if you use nixio, which does the following:
```
local socket = require 'nixio'
sched.get_time = function()
  local sec, usec = nixio.gettimeofday()
  return sec + usec/1000000
end
sched.idle = function (t)
  local sec = floor(t)
  local nsec = (t-sec)*1000000000
  nixio.nanosleep(sec, nsec)
end
```
You can use them as examples if you something else.

**Comment by milrrenmattar** [comment]
Hey! I've tried the first option, the socket thing and, unfortunately, but even using the luasocket, I got an error message saying that I haven't the Socket.core....

Still working on that but, well, any tips?

**Comment by xopxe** [comment]
That probably means there is something weird with your luasocket installation. Can you  use luasocket from a simple lua script? Something as simple as 
```
require  'socket'
print(socket.gettime())
```

**Comment by milrrenmattar** [comment]
Yeah, it doesn't work...
I think it should be something wrong in my makefile... as I made it on a little rush.
I'll check this and stuff. Thanks for helping me!
