### ISSUE TITLE
single file distribution

### ISSUE THREAD

**Issue by denisdemais** [xopxe/lumen#15]
Hi.
I try'ng to uses Lumen, but, the filesystem don't supporte directories.

Is possible to load lumen in a single file? I.e., local lumen = require('lumen.all.in.one.lua'); ?

thanks

**Comment by xopxe** [comment]
On what platform you are trying? If it is a microcontroller or something like that you can look in https://github.com/xopxe/eLumen , a one file version of lumen with lots of things stripped down.

**Comment by denisdemais** [comment]
I'm running Lua 5.1.5 at arm11 (custom board) and lumen is a useful! (i'm learning yet)
Also will uses @ NodeMCU [ESP8266]

one single file [all-in-one] is very useful.

i will try eLumen!

thanks
