### ISSUE TITLE
on task completion emit `DIE` and `FINISH` signals lazily?

### ISSUE THREAD

**Issue by lePereT** [xopxe/lumen#23]
I'm trying to wait until two Lumen tasks have finished, basically using the following code:

```lua
a = sched.new_task(function()
    -- Does some work
end)

b = sched.new_task(function()
    -- Does some work
end)

while a.status == 'ready' or b.status == 'ready' do
    sched.wait({a.EVENT_DIE, a.EVENT_FINISH, b.EVENT_DIE, b.EVENT_FINISH})
end 
```
This doesn't work, because the following lines in `sched.lua` emit these signals before changing the `status` of the task.

https://github.com/xopxe/lumen/blob/efa8e6b7b8691b44f6ab210fd8e5be352d5ab8c2/sched.lua#L133

Therefore we have the strange situation where anything woken up by a signal saying a task has ended, when checking the status of the task, will find that the task remains `ready`. Should the status be changed earlier? Or should the signals be emitted lazily? Or is there a better way of doing what I'm attempting?

**Comment by lePereT** [comment]
For the moment I've worked around this by examining the status of the underlying coroutine but this seems a little hacky

**Comment by xopxe** [comment]
Yes, I agree that you code seems perfectly reasonable.
As you say there two solutions, wither mark it as dead as soon as we know the coroutine is dead, or delay the signal until after the death of the task is completed.
The first solution would be move the line 144  (_taskd.status='dead'_)  to line 129.
The other would be changing the four _emit_signal_ on lines 133, 134, 138 and 139 to _M.schedule_signal_.
I believe the first option of marking the task as dead before signalling is the simplest way. Could you test it?

**Comment by lePereT** [comment]
I will!
(I've also seen the discussion on the Lua mailing list re the Trio implementation that's being done. It seems interesting but it still seems to suffer from the function colouring problem. I'd wondered whether you'd seen Andy Wingo's post on fibers (CML) in Lua. It's a very beautiful thing https://wingolog.org/archives/2018/05/16/lightweight-concurrency-in-lua . There's a fuller implementation in the Snabb fibers library that he authored https://github.com/snabbco/snabb/tree/master/src/lib/fibers . I've made some of the code there standalone but haven't had time to do the epoll stuff. Anyway, though this might be of interest to you, as some nice building blocks)

**Comment by xopxe** [comment]
committed  ## e56e64c75ee92092cd087b633d5a173f01cde210

**Comment by lePereT** [comment]
Sorry I didn't get time to test this Xopxe!
